server:
  port: 8001

spring:
    application:
        name: course-service
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true

    instance:
        prefer-ip-address: true
        
message: Hello Course service from Config Server. Here is your configuration.Thank you.
