server:
  port: 8001

spring:
    application:
        name: course-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: mayank1234
        url: jdbc:mysql://localhost:3306/studentmanagementsystem
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        prefer-ip-address: true
        
message: Hello Course service from Config Server. Here is your configuration.
