spring:
  application:
    name: eureka-server-service
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
message: Hello..
